version: 1.0

# 代码风格
style:
  typescript:
    semi: false              # 不使用分号
    singleQuote: true       # 使用单引号
    trailingComma: 'es5'    # ES5 风格的尾逗号
    tabWidth: 2             # 缩进宽度
    printWidth: 80          # 每行最大长度

# 组件规范
components:
  - 使用函数式组件
  - 使用 TypeScript
  - 使用 CSS Modules 或 Tailwind
  - 组件文件使用 PascalCase 命名

# 文件组织
structure:
  - 相关组件放在同一目录
  - 共享组件放在 components/ui
  - 页面组件放在 app 目录
  - 工具函数放在 lib 目录 